import {
  BMW_M3_CS_G80_SPEC,
  BMW_M3_CS_G80_RENDER_PROFILE_REAL,
  BMW_M3_CS_G80_RENDER_PROFILE_GAME,
} from './bmw_m3_cs';
import {
  PORSCHE_911_GT3RS_SPEC,
  PORSCHE_911_GT3RS_RENDER_PROFILE_REAL,
  PORSCHE_911_GT3RS_RENDER_PROFILE_GAME,
} from './porsche_911_gt3rs';
import {
  MERCEDES_AMG_GT_R_SPEC,
  MERCEDES_AMG_GT_R_RENDER_PROFILE_REAL,
  MERCEDES_AMG_GT_R_RENDER_PROFILE_GAME,
} from './mercedes_amg_gt_r';
import type { CarSpec, CarRenderProfile } from './types';

export type CarDatabaseEntry = {
  spec: CarSpec;
  renderProfiles: Record<string, CarRenderProfile>;
};

export const carSpecs = {
  [BMW_M3_CS_G80_SPEC.id]: BMW_M3_CS_G80_SPEC,
  [PORSCHE_911_GT3RS_SPEC.id]: PORSCHE_911_GT3RS_SPEC,
  [MERCEDES_AMG_GT_R_SPEC.id]: MERCEDES_AMG_GT_R_SPEC,
};

export const carRenderProfiles = {
  [BMW_M3_CS_G80_RENDER_PROFILE_REAL.id]: BMW_M3_CS_G80_RENDER_PROFILE_REAL,
  [BMW_M3_CS_G80_RENDER_PROFILE_GAME.id]: BMW_M3_CS_G80_RENDER_PROFILE_GAME,
  [PORSCHE_911_GT3RS_RENDER_PROFILE_REAL.id]: PORSCHE_911_GT3RS_RENDER_PROFILE_REAL,
  [PORSCHE_911_GT3RS_RENDER_PROFILE_GAME.id]: PORSCHE_911_GT3RS_RENDER_PROFILE_GAME,
  [MERCEDES_AMG_GT_R_RENDER_PROFILE_REAL.id]: MERCEDES_AMG_GT_R_RENDER_PROFILE_REAL,
  [MERCEDES_AMG_GT_R_RENDER_PROFILE_GAME.id]: MERCEDES_AMG_GT_R_RENDER_PROFILE_GAME,
};

export const carDatabase: Record<string, CarDatabaseEntry> = {
  [BMW_M3_CS_G80_SPEC.id]: {
    spec: BMW_M3_CS_G80_SPEC,
    renderProfiles: {
      [BMW_M3_CS_G80_RENDER_PROFILE_REAL.id]: BMW_M3_CS_G80_RENDER_PROFILE_REAL,
      [BMW_M3_CS_G80_RENDER_PROFILE_GAME.id]: BMW_M3_CS_G80_RENDER_PROFILE_GAME,
    },
  },
  [PORSCHE_911_GT3RS_SPEC.id]: {
    spec: PORSCHE_911_GT3RS_SPEC,
    renderProfiles: {
      [PORSCHE_911_GT3RS_RENDER_PROFILE_REAL.id]: PORSCHE_911_GT3RS_RENDER_PROFILE_REAL,
      [PORSCHE_911_GT3RS_RENDER_PROFILE_GAME.id]: PORSCHE_911_GT3RS_RENDER_PROFILE_GAME,
    },
  },
  [MERCEDES_AMG_GT_R_SPEC.id]: {
    spec: MERCEDES_AMG_GT_R_SPEC,
    renderProfiles: {
      [MERCEDES_AMG_GT_R_RENDER_PROFILE_REAL.id]: MERCEDES_AMG_GT_R_RENDER_PROFILE_REAL,
      [MERCEDES_AMG_GT_R_RENDER_PROFILE_GAME.id]: MERCEDES_AMG_GT_R_RENDER_PROFILE_GAME,
    },
  },
};
